### ISSUE TITLE
which wire of the 4-pin PWM fan corresponds to FAN1-/FAN2-/FAN3-/FAN4-?

### ISSUE THREAD

**Issue by bbluvgg** [ELFROTomaszFronczek/ESP8266_FAN_Controller#1]
In your circuit diagram, which wire of the 4-pin PWM fan corresponds to FAN1-/FAN2-/FAN3-/FAN4-? What is the purpose of the capacitor across pins 8 and 5 of the TLP251 in the diagram?

**Comment by ELFROTomaszFronczek** [comment]
The capacitor is simply in the specifications of this chip.
![obraz](https://github.com/user-attachments/assets/3814c385-0ca9-4760-9eb7-192851386050)

**Comment by ELFROTomaszFronczek** [comment]
The outputs are visible in the diagram and are in order from top 1 to 4. 
D1-FAN1 D2-FAN2 D3-FAN3 D6-FAN4
![obraz](https://github.com/user-attachments/assets/e82a70de-078c-4873-80a6-6df2531b36b4) 
![obraz](https://github.com/user-attachments/assets/1908fe08-a1d6-4e80-8b6c-e232f9c36311)
